services:
  - type: web
    name: zesfin-api
    runtime: docker
    region: frankfurt
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: zesfin-db
          property: connectionString
      - key: DATABASE_USERNAME
        fromDatabase:
          name: zesfin-db
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: zesfin-db
          property: password
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: JWT_SECRET
        sync: false
    healthCheckPath: /actuator/health

databases:
  - name: zesfin-db
    plan: free
    databaseName: zesfin
    user: zesfin_user
    region: frankfurt
